build:ecommerce-images:
  script:
    - apk add --no-cache docker
    - python setup.py install
    - tutor plugins enable discovery
    - tutor plugins enable ecommerce
    - tutor config save
    - tutor images build ecommerce
    - tutor images build ecommerce_worker
  only:
    refs:
      - master
  tags:
    - private
  stage: build

deploy:images:
  script:
    - apk add --no-cache docker
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - python setup.py install
    - tutor plugins enable discovery
    - tutor plugins enable ecommerce
    - tutor config save
    - tutor images push ecommerce
    - tutor images push ecommerce_worker
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy

deploy:pypi:
  script:
    - pip3 install -U setuptools twine
    - python3 setup.py sdist
    - twine upload --skip-existing dist/tutor-ecommerce*.tar.gz
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy
